version: '2'
services:
    devoxx-app:
        image: devoxx
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://devoxx-mysql:3306/devoxx?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    devoxx-mysql:
        extends:
            file: mysql.yml
            service: devoxx-mysql
